`timescale 1ns / 1ps

module interface_gtx_8ch_separate(
    // system
    input  wire [7:0] rx_pma_rst_n,

    // 100MHz DRP clock
    input  wire clk_drp_100M,

    // 125MHz GTX ref clock
    input  wire clk_gtx_125M,

    // GTX IO
    output wire [7:0] gtx_tx_p,
                        gtx_tx_n,
    input  wire [7:0] gtx_rx_p,
                        gtx_rx_n,

    // 125MHz TX, RX out clock
    output wire [7:0] clk_txoutclk_bufg,
                        clk_rxoutclk_bufg,

    // GTX data
    input  wire [127:0] gt_tx_data,
    input  wire [7:0] gt_tx_data_valid,
    output wire [127:0] gt_rx_data,
    output wire [7:0] gt_rx_data_valid,

    // states for alignment
    output wire [7:0] gtx_cpll_is_lock,
    output wire [7:0] gtx_cpll_fbclk_lost,
    output wire [7:0] rx_reset_done,
    output wire [15:0] rx_data_is_comma,
    output wire [7:0] gtx_rx_error
    );

    // txoutclk / rxoutclk buffers
    wire clk_txoutclk [0:7];
    wire clk_rxoutclk [0:7];

    genvar i;
    generate
        for (i = 0; i < 8; i = i + 1) begin : gen_bufg
            BUFG instance_bufg_txoutclk(
                .I (clk_txoutclk[i]),
                .O (clk_txoutclk_bufg[i])
            );
            BUFG instance_bufg_rxoutclk(
                .I (clk_rxoutclk[i]),
                .O (clk_rxoutclk_bufg[i])
            );
        end
    endgenerate

    // flags
    wire [1:0] tx_data_is_k [0:7];
    wire [1:0] rx_data_is_k [0:7];
    wire [1:0] rx_not_in_table [0:7];

    generate
        for (i = 0; i < 8; i = i + 1) begin : gen_flags
            assign tx_data_is_k[i] = gt_tx_data_valid[i] ? 2'b00 : 2'b11;
            assign gt_rx_data_valid[i] = (rx_data_is_k[i] == 2'b00) ? 1 : 0;
            assign gtx_rx_error[i] = |rx_not_in_table[i];
        end
    endgenerate

    //-------- 8 single-channel GTX IPs (gt_phy_ch0..ch7) --------
    // GT0 (X1Y4)
    gt_phy_ch0 u_gt_phy_ch0 (
        .sysclk_in                  (clk_drp_100M),
        .soft_reset_tx_in           (1'b0),
        .soft_reset_rx_in           (1'b0),
        .dont_reset_on_data_error_in (1'b0),
        .gt0_data_valid_in          (1'b1),
        .gt0_cpllfbclklost_out      (),
        .gt0_cplllock_out           (gtx_cpll_is_lock[0]),
        .gt0_cplllockdetclk_in      (clk_drp_100M),
        .gt0_cpllreset_in           (cpll_reset),
        .gt0_gtrefclk0_in           (1'b0),
        .gt0_gtrefclk1_in           (clk_gtx_125M),
        .gt0_drpaddr_in             (9'b0),
        .gt0_drpclk_in              (clk_drp_100M),
        .gt0_drpdi_in               (16'b0),
        .gt0_drpdo_out              (),
        .gt0_drpen_in               (1'b0),
        .gt0_drprdy_out             (),
        .gt0_drpwe_in               (1'b0),
        .gt0_dmonitorout_out        (),
        .gt0_rxpd_in                (2'b0),
        .gt0_txpd_in                (2'b0),
        .gt0_eyescanreset_in        (1'b0),
        .gt0_rxuserrdy_in           (1'b1),
        .gt0_eyescandataerror_out   (),
        .gt0_eyescantrigger_in      (1'b0),
        .gt0_rxusrclk_in            (clk_rxoutclk_bufg[0]),
        .gt0_rxusrclk2_in           (clk_rxoutclk_bufg[0]),
        .gt0_rxdata_out             (gt_rx_data[0 +: 16]),
        .gt0_rxdisperr_out          (),
        .gt0_rxnotintable_out       (rx_not_in_table[0]),
        .gt0_gtxrxp_in              (gtx_rx_p[0]),
        .gt0_gtxrxn_in              (gtx_rx_n[0]),
        .gt0_rxphmonitor_out        (),
        .gt0_rxphslipmonitor_out    (),
        .gt0_rxdfelpmreset_in       (1'b0),
        .gt0_rxmonitorout_out       (),
        .gt0_rxmonitorsel_in        (2'b0),
        .gt0_rxoutclk_out           (clk_rxoutclk[0]),
        .gt0_rxoutclkfabric_out     (),
        .gt0_gtrxreset_in           (1'b0),
        .gt0_rxpmareset_in          (~rx_pma_rst_n[0]),
        .gt0_rxchariscomma_out      (rx_data_is_comma[0 +: 2]),
        .gt0_rxcharisk_out          (rx_data_is_k[0]),
        .gt0_rxresetdone_out        (rx_reset_done[0]),
        .gt0_gttxreset_in           (1'b0),
        .gt0_txuserrdy_in           (1'b1),
        .gt0_txusrclk_in            (clk_txoutclk_bufg[0]),
        .gt0_txusrclk2_in           (clk_txoutclk_bufg[0]),
        .gt0_txelecidle_in          (1'b0),
        // .gt0_txdata_in              (gt_tx_data[0 +: 16]),
        .gt0_txdata_in              (16'hbc3c),
        .gt0_gtxtxn_out             (gtx_tx_n[0]),
        .gt0_gtxtxp_out             (gtx_tx_p[0]),
        .gt0_txoutclk_out           (clk_txoutclk[0]),
        .gt0_txoutclkfabric_out     (),
        .gt0_txoutclkpcs_out        (),
        .gt0_txcharisk_in           (2'b11),
        .gt0_txresetdone_out        (),
        .gt0_qplloutclk_in          (1'b0),
        .gt0_qplloutrefclk_in       (1'b0)
    );

    // GT1 (X1Y5)
    gt_phy_ch1 u_gt_phy_ch1 (
        .sysclk_in                  (clk_drp_100M),
        .soft_reset_tx_in           (1'b0),
        .soft_reset_rx_in           (1'b0),
        .dont_reset_on_data_error_in (1'b0),
        .gt0_data_valid_in          (1'b1),
        .gt0_cpllfbclklost_out      (),
        .gt0_cplllock_out           (gtx_cpll_is_lock[1]),
        .gt0_cplllockdetclk_in      (clk_drp_100M),
        .gt0_cpllreset_in           (cpll_reset),
        .gt0_gtrefclk0_in           (1'b0),
        .gt0_gtrefclk1_in           (clk_gtx_125M),
        .gt0_drpaddr_in             (9'b0),
        .gt0_drpclk_in              (clk_drp_100M),
        .gt0_drpdi_in               (16'b0),
        .gt0_drpdo_out              (),
        .gt0_drpen_in               (1'b0),
        .gt0_drprdy_out             (),
        .gt0_drpwe_in               (1'b0),
        .gt0_dmonitorout_out        (),
        .gt0_rxpd_in                (2'b0),
        .gt0_txpd_in                (2'b0),
        .gt0_eyescanreset_in        (1'b0),
        .gt0_rxuserrdy_in           (1'b1),
        .gt0_eyescandataerror_out   (),
        .gt0_eyescantrigger_in      (1'b0),
        .gt0_rxusrclk_in            (clk_rxoutclk_bufg[1]),
        .gt0_rxusrclk2_in           (clk_rxoutclk_bufg[1]),
        .gt0_rxdata_out             (gt_rx_data[16 +: 16]),
        .gt0_rxdisperr_out          (),
        .gt0_rxnotintable_out       (rx_not_in_table[1]),
        .gt0_gtxrxp_in              (gtx_rx_p[1]),
        .gt0_gtxrxn_in              (gtx_rx_n[1]),
        .gt0_rxphmonitor_out        (),
        .gt0_rxphslipmonitor_out    (),
        .gt0_rxdfelpmreset_in       (1'b0),
        .gt0_rxmonitorout_out       (),
        .gt0_rxmonitorsel_in        (2'b0),
        .gt0_rxoutclk_out           (clk_rxoutclk[1]),
        .gt0_rxoutclkfabric_out     (),
        .gt0_gtrxreset_in           (1'b0),
        .gt0_rxpmareset_in          (~rx_pma_rst_n[1]),
        .gt0_rxchariscomma_out      (rx_data_is_comma[2 +: 2]),
        .gt0_rxcharisk_out          (rx_data_is_k[1]),
        .gt0_rxresetdone_out        (rx_reset_done[1]),
        .gt0_gttxreset_in           (1'b0),
        .gt0_txuserrdy_in           (1'b1),
        .gt0_txusrclk_in            (clk_txoutclk_bufg[1]),
        .gt0_txusrclk2_in           (clk_txoutclk_bufg[1]),
        .gt0_txelecidle_in          (1'b0),
        // .gt0_txdata_in              (gt_tx_data[16 +: 16]),
        .gt0_txdata_in              (16'hbc3c),
        .gt0_gtxtxn_out             (gtx_tx_n[1]),
        .gt0_gtxtxp_out             (gtx_tx_p[1]),
        .gt0_txoutclk_out           (clk_txoutclk[1]),
        .gt0_txoutclkfabric_out     (),
        .gt0_txoutclkpcs_out        (),
        .gt0_txcharisk_in           (2'b11),
        .gt0_txresetdone_out        (),
        .gt0_qplloutclk_in          (1'b0),
        .gt0_qplloutrefclk_in       (1'b0)
    );

    // GT2 (X1Y6)
    gt_phy_ch2 u_gt_phy_ch2 (
        .sysclk_in                  (clk_drp_100M),
        .soft_reset_tx_in           (1'b0),
        .soft_reset_rx_in           (1'b0),
        .dont_reset_on_data_error_in (1'b0),
        .gt0_data_valid_in          (1'b1),
        .gt0_cpllfbclklost_out      (),
        .gt0_cplllock_out           (gtx_cpll_is_lock[2]),
        .gt0_cplllockdetclk_in      (clk_drp_100M),
        .gt0_cpllreset_in           (cpll_reset),
        .gt0_gtrefclk0_in           (1'b0),
        .gt0_gtrefclk1_in           (clk_gtx_125M),
        .gt0_drpaddr_in             (9'b0),
        .gt0_drpclk_in              (clk_drp_100M),
        .gt0_drpdi_in               (16'b0),
        .gt0_drpdo_out              (),
        .gt0_drpen_in               (1'b0),
        .gt0_drprdy_out             (),
        .gt0_drpwe_in               (1'b0),
        .gt0_dmonitorout_out        (),
        .gt0_rxpd_in                (2'b0),
        .gt0_txpd_in                (2'b0),
        .gt0_eyescanreset_in        (1'b0),
        .gt0_rxuserrdy_in           (1'b1),
        .gt0_eyescandataerror_out   (),
        .gt0_eyescantrigger_in      (1'b0),
        .gt0_rxusrclk_in            (clk_rxoutclk_bufg[2]),
        .gt0_rxusrclk2_in           (clk_rxoutclk_bufg[2]),
        .gt0_rxdata_out             (gt_rx_data[32 +: 16]),
        .gt0_rxdisperr_out          (),
        .gt0_rxnotintable_out       (rx_not_in_table[2]),
        .gt0_gtxrxp_in              (gtx_rx_p[2]),
        .gt0_gtxrxn_in              (gtx_rx_n[2]),
        .gt0_rxphmonitor_out        (),
        .gt0_rxphslipmonitor_out    (),
        .gt0_rxdfelpmreset_in       (1'b0),
        .gt0_rxmonitorout_out       (),
        .gt0_rxmonitorsel_in        (2'b0),
        .gt0_rxoutclk_out           (clk_rxoutclk[2]),
        .gt0_rxoutclkfabric_out     (),
        .gt0_gtrxreset_in           (1'b0),
        .gt0_rxpmareset_in          (~rx_pma_rst_n[2]),
        .gt0_rxchariscomma_out      (rx_data_is_comma[4 +: 2]),
        .gt0_rxcharisk_out          (rx_data_is_k[2]),
        .gt0_rxresetdone_out        (rx_reset_done[2]),
        .gt0_gttxreset_in           (1'b0),
        .gt0_txuserrdy_in           (1'b1),
        .gt0_txusrclk_in            (clk_txoutclk_bufg[2]),
        .gt0_txusrclk2_in           (clk_txoutclk_bufg[2]),
        .gt0_txelecidle_in          (1'b0),
        // .gt0_txdata_in              (gt_tx_data[32 +: 16]),
        .gt0_txdata_in              (16'hbc3c),
        .gt0_gtxtxn_out             (gtx_tx_n[2]),
        .gt0_gtxtxp_out             (gtx_tx_p[2]),
        .gt0_txoutclk_out           (clk_txoutclk[2]),
        .gt0_txoutclkfabric_out     (),
        .gt0_txoutclkpcs_out        (),
        .gt0_txcharisk_in           (2'b11),
        .gt0_txresetdone_out        (),
        .gt0_qplloutclk_in          (1'b0),
        .gt0_qplloutrefclk_in       (1'b0)
    );

    // GT3 (X1Y7)
    gt_phy_ch3 u_gt_phy_ch3 (
        .sysclk_in                  (clk_drp_100M),
        .soft_reset_tx_in           (1'b0),
        .soft_reset_rx_in           (1'b0),
        .dont_reset_on_data_error_in (1'b0),
        .gt0_data_valid_in          (1'b1),
        .gt0_cpllfbclklost_out      (),
        .gt0_cplllock_out           (gtx_cpll_is_lock[3]),
        .gt0_cplllockdetclk_in      (clk_drp_100M),
        .gt0_cpllreset_in           (cpll_reset),
        .gt0_gtrefclk0_in           (1'b0),
        .gt0_gtrefclk1_in           (clk_gtx_125M),
        .gt0_drpaddr_in             (9'b0),
        .gt0_drpclk_in              (clk_drp_100M),
        .gt0_drpdi_in               (16'b0),
        .gt0_drpdo_out              (),
        .gt0_drpen_in               (1'b0),
        .gt0_drprdy_out             (),
        .gt0_drpwe_in               (1'b0),
        .gt0_dmonitorout_out        (),
        .gt0_rxpd_in                (2'b0),
        .gt0_txpd_in                (2'b0),
        .gt0_eyescanreset_in        (1'b0),
        .gt0_rxuserrdy_in           (1'b1),
        .gt0_eyescandataerror_out   (),
        .gt0_eyescantrigger_in      (1'b0),
        .gt0_rxusrclk_in            (clk_rxoutclk_bufg[3]),
        .gt0_rxusrclk2_in           (clk_rxoutclk_bufg[3]),
        .gt0_rxdata_out             (gt_rx_data[48 +: 16]),
        .gt0_rxdisperr_out          (),
        .gt0_rxnotintable_out       (rx_not_in_table[3]),
        .gt0_gtxrxp_in              (gtx_rx_p[3]),
        .gt0_gtxrxn_in              (gtx_rx_n[3]),
        .gt0_rxphmonitor_out        (),
        .gt0_rxphslipmonitor_out    (),
        .gt0_rxdfelpmreset_in       (1'b0),
        .gt0_rxmonitorout_out       (),
        .gt0_rxmonitorsel_in        (2'b0),
        .gt0_rxoutclk_out           (clk_rxoutclk[3]),
        .gt0_rxoutclkfabric_out     (),
        .gt0_gtrxreset_in           (1'b0),
        .gt0_rxpmareset_in          (~rx_pma_rst_n[3]),
        .gt0_rxchariscomma_out      (rx_data_is_comma[6 +: 2]),
        .gt0_rxcharisk_out          (rx_data_is_k[3]),
        .gt0_rxresetdone_out        (rx_reset_done[3]),
        .gt0_gttxreset_in           (1'b0),
        .gt0_txuserrdy_in           (1'b1),
        .gt0_txusrclk_in            (clk_txoutclk_bufg[3]),
        .gt0_txusrclk2_in           (clk_txoutclk_bufg[3]),
        .gt0_txelecidle_in          (1'b0),
        // .gt0_txdata_in              (gt_tx_data[48 +: 16]),
        .gt0_txdata_in              (16'hbc3c),
        .gt0_gtxtxn_out             (gtx_tx_n[3]),
        .gt0_gtxtxp_out             (gtx_tx_p[3]),
        .gt0_txoutclk_out           (clk_txoutclk[3]),
        .gt0_txoutclkfabric_out     (),
        .gt0_txoutclkpcs_out        (),
        .gt0_txcharisk_in           (2'b11),
        .gt0_txresetdone_out        (),
        .gt0_qplloutclk_in          (1'b0),
        .gt0_qplloutrefclk_in       (1'b0)
    );

    // GT4 (X1Y12)
    gt_phy_ch4 u_gt_phy_ch4 (
        .sysclk_in                  (clk_drp_100M),
        .soft_reset_tx_in           (1'b0),
        .soft_reset_rx_in           (1'b0),
        .dont_reset_on_data_error_in(1'b0),
        .gt0_data_valid_in          (1'b1),
        .gt0_cpllfbclklost_out      (),
        .gt0_cplllock_out           (gtx_cpll_is_lock[4]),
        .gt0_cplllockdetclk_in      (clk_drp_100M),
        .gt0_cpllreset_in           (cpll_reset),
        .gt0_gtrefclk0_in           (1'b0),
        .gt0_gtrefclk1_in           (clk_gtx_125M),
        .gt0_drpaddr_in             (9'b0),
        .gt0_drpclk_in              (clk_drp_100M),
        .gt0_drpdi_in               (16'b0),
        .gt0_drpdo_out              (),
        .gt0_drpen_in               (1'b0),
        .gt0_drprdy_out             (),
        .gt0_drpwe_in               (1'b0),
        .gt0_dmonitorout_out        (),
        .gt0_rxpd_in                (2'b0),
        .gt0_txpd_in                (2'b0),
        .gt0_eyescanreset_in        (1'b0),
        .gt0_rxuserrdy_in           (1'b1),
        .gt0_eyescandataerror_out   (),
        .gt0_eyescantrigger_in      (1'b0),
        .gt0_rxusrclk_in            (clk_rxoutclk_bufg[4]),
        .gt0_rxusrclk2_in           (clk_rxoutclk_bufg[4]),
        .gt0_rxdata_out             (gt_rx_data[64 +: 16]),
        .gt0_rxdisperr_out          (),
        .gt0_rxnotintable_out       (rx_not_in_table[4]),
        .gt0_gtxrxp_in              (gtx_rx_p[4]),
        .gt0_gtxrxn_in              (gtx_rx_n[4]),
        .gt0_rxphmonitor_out        (),
        .gt0_rxphslipmonitor_out    (),
        .gt0_rxdfelpmreset_in       (1'b0),
        .gt0_rxmonitorout_out       (),
        .gt0_rxmonitorsel_in        (2'b0),
        .gt0_rxoutclk_out           (clk_rxoutclk[4]),
        .gt0_rxoutclkfabric_out     (),
        .gt0_gtrxreset_in           (1'b0),
        .gt0_rxpmareset_in          (~rx_pma_rst_n[4]),
        .gt0_rxchariscomma_out      (rx_data_is_comma[8 +: 2]),
        .gt0_rxcharisk_out          (rx_data_is_k[4]),
        .gt0_rxresetdone_out        (rx_reset_done[4]),
        .gt0_gttxreset_in           (1'b0),
        .gt0_txuserrdy_in           (1'b1),
        .gt0_txusrclk_in            (clk_txoutclk_bufg[4]),
        .gt0_txusrclk2_in           (clk_txoutclk_bufg[4]),
        .gt0_txelecidle_in          (1'b0),
        // .gt0_txdata_in              (gt_tx_data[64 +: 16]),
        .gt0_txdata_in              (16'hbc3c),
        .gt0_gtxtxn_out             (gtx_tx_n[4]),
        .gt0_gtxtxp_out             (gtx_tx_p[4]),
        .gt0_txoutclk_out           (clk_txoutclk[4]),
        .gt0_txoutclkfabric_out     (),
        .gt0_txoutclkpcs_out        (),
        .gt0_txcharisk_in           (2'b11),
        .gt0_txresetdone_out        (),
        .gt0_qplloutclk_in          (1'b0),
        .gt0_qplloutrefclk_in       (1'b0)
    );

    // GT5 (X1Y13)
    gt_phy_ch5 u_gt_phy_ch5 (
        .sysclk_in                  (clk_drp_100M),
        .soft_reset_tx_in           (1'b0),
        .soft_reset_rx_in           (1'b0),
        .dont_reset_on_data_error_in (1'b0),
        .gt0_data_valid_in          (1'b1),
        .gt0_cpllfbclklost_out      (),
        .gt0_cplllock_out           (gtx_cpll_is_lock[5]),
        .gt0_cplllockdetclk_in      (clk_drp_100M),
        .gt0_cpllreset_in           (cpll_reset),
        .gt0_gtrefclk0_in           (1'b0),
        .gt0_gtrefclk1_in           (clk_gtx_125M),
        .gt0_drpaddr_in             (9'b0),
        .gt0_drpclk_in              (clk_drp_100M),
        .gt0_drpdi_in               (16'b0),
        .gt0_drpdo_out              (),
        .gt0_drpen_in               (1'b0),
        .gt0_drprdy_out             (),
        .gt0_drpwe_in               (1'b0),
        .gt0_dmonitorout_out        (),
        .gt0_rxpd_in                (2'b0),
        .gt0_txpd_in                (2'b0),
        .gt0_eyescanreset_in        (1'b0),
        .gt0_rxuserrdy_in           (1'b1),
        .gt0_eyescandataerror_out   (),
        .gt0_eyescantrigger_in      (1'b0),
        .gt0_rxusrclk_in            (clk_rxoutclk_bufg[5]),
        .gt0_rxusrclk2_in           (clk_rxoutclk_bufg[5]),
        .gt0_rxdata_out             (gt_rx_data[80 +: 16]),
        .gt0_rxdisperr_out          (),
        .gt0_rxnotintable_out       (rx_not_in_table[5]),
        .gt0_gtxrxp_in              (gtx_rx_p[5]),
        .gt0_gtxrxn_in              (gtx_rx_n[5]),
        .gt0_rxphmonitor_out        (),
        .gt0_rxphslipmonitor_out    (),
        .gt0_rxdfelpmreset_in       (1'b0),
        .gt0_rxmonitorout_out       (),
        .gt0_rxmonitorsel_in        (2'b0),
        .gt0_rxoutclk_out           (clk_rxoutclk[5]),
        .gt0_rxoutclkfabric_out     (),
        .gt0_gtrxreset_in           (1'b0),
        .gt0_rxpmareset_in          (~rx_pma_rst_n[5]),
        .gt0_rxchariscomma_out      (rx_data_is_comma[10 +: 2]),
        .gt0_rxcharisk_out          (rx_data_is_k[5]),
        .gt0_rxresetdone_out        (rx_reset_done[5]),
        .gt0_gttxreset_in           (1'b0),
        .gt0_txuserrdy_in           (1'b1),
        .gt0_txusrclk_in            (clk_txoutclk_bufg[5]),
        .gt0_txusrclk2_in           (clk_txoutclk_bufg[5]),
        .gt0_txelecidle_in          (1'b0),
        // .gt0_txdata_in              (gt_tx_data[80 +: 16]),
        .gt0_txdata_in              (16'hbc3c),
        .gt0_gtxtxn_out             (gtx_tx_n[5]),
        .gt0_gtxtxp_out             (gtx_tx_p[5]),
        .gt0_txoutclk_out           (clk_txoutclk[5]),
        .gt0_txoutclkfabric_out     (),
        .gt0_txoutclkpcs_out        (),
        .gt0_txcharisk_in           (2'b11),
        .gt0_txresetdone_out        (),
        .gt0_qplloutclk_in          (1'b0),
        .gt0_qplloutrefclk_in       (1'b0)
    );

    // GT6 (X1Y14)
    gt_phy_ch6 u_gt_phy_ch6 (
        .sysclk_in                  (clk_drp_100M),
        .soft_reset_tx_in           (1'b0),
        .soft_reset_rx_in           (1'b0),
        .dont_reset_on_data_error_in (1'b0),
        .gt0_data_valid_in          (1'b1),
        .gt0_cpllfbclklost_out      (),
        .gt0_cplllock_out           (gtx_cpll_is_lock[6]),
        .gt0_cplllockdetclk_in      (clk_drp_100M),
        .gt0_cpllreset_in           (cpll_reset),
        .gt0_gtrefclk0_in           (1'b0),
        .gt0_gtrefclk1_in           (clk_gtx_125M),
        .gt0_drpaddr_in             (9'b0),
        .gt0_drpclk_in              (clk_drp_100M),
        .gt0_drpdi_in               (16'b0),
        .gt0_drpdo_out              (),
        .gt0_drpen_in               (1'b0),
        .gt0_drprdy_out             (),
        .gt0_drpwe_in               (1'b0),
        .gt0_dmonitorout_out        (),
        .gt0_rxpd_in                (2'b0),
        .gt0_txpd_in                (2'b0),
        .gt0_eyescanreset_in        (1'b0),
        .gt0_rxuserrdy_in           (1'b1),
        .gt0_eyescandataerror_out   (),
        .gt0_eyescantrigger_in      (1'b0),
        .gt0_rxusrclk_in            (clk_rxoutclk_bufg[6]),
        .gt0_rxusrclk2_in           (clk_rxoutclk_bufg[6]),
        .gt0_rxdata_out             (gt_rx_data[96 +: 16]),
        .gt0_rxdisperr_out          (),
        .gt0_rxnotintable_out       (rx_not_in_table[6]),
        .gt0_gtxrxp_in              (gtx_rx_p[6]),
        .gt0_gtxrxn_in              (gtx_rx_n[6]),
        .gt0_rxphmonitor_out        (),
        .gt0_rxphslipmonitor_out    (),
        .gt0_rxdfelpmreset_in       (1'b0),
        .gt0_rxmonitorout_out       (),
        .gt0_rxmonitorsel_in        (2'b0),
        .gt0_rxoutclk_out           (clk_rxoutclk[6]),
        .gt0_rxoutclkfabric_out     (),
        .gt0_gtrxreset_in           (1'b0),
        .gt0_rxpmareset_in          (~rx_pma_rst_n[6]),
        .gt0_rxchariscomma_out      (rx_data_is_comma[12 +: 2]),
        .gt0_rxcharisk_out          (rx_data_is_k[6]),
        .gt0_rxresetdone_out        (rx_reset_done[6]),
        .gt0_gttxreset_in           (1'b0),
        .gt0_txuserrdy_in           (1'b1),
        .gt0_txusrclk_in            (clk_txoutclk_bufg[6]),
        .gt0_txusrclk2_in           (clk_txoutclk_bufg[6]),
        .gt0_txelecidle_in          (1'b0),
        // .gt0_txdata_in              (gt_tx_data[96 +: 16]),
        .gt0_txdata_in              (16'hbc3c),
        .gt0_gtxtxn_out             (gtx_tx_n[6]),
        .gt0_gtxtxp_out             (gtx_tx_p[6]),
        .gt0_txoutclk_out           (clk_txoutclk[6]),
        .gt0_txoutclkfabric_out     (),
        .gt0_txoutclkpcs_out        (),
        .gt0_txcharisk_in           (2'b11),
        .gt0_txresetdone_out        (),
        .gt0_qplloutclk_in          (1'b0),
        .gt0_qplloutrefclk_in       (1'b0)
    );

    // GT7 (X1Y15)
    gt_phy_ch7 u_gt_phy_ch7 (
        .sysclk_in                  (clk_drp_100M),
        .soft_reset_tx_in           (1'b0),
        .soft_reset_rx_in           (1'b0),
        .dont_reset_on_data_error_in (1'b0),
        .gt0_data_valid_in          (1'b1),
        .gt0_cpllfbclklost_out      (),
        .gt0_cplllock_out           (gtx_cpll_is_lock[7]),
        .gt0_cplllockdetclk_in      (clk_drp_100M),
        .gt0_cpllreset_in           (cpll_reset),
        .gt0_gtrefclk0_in           (1'b0),
        .gt0_gtrefclk1_in           (clk_gtx_125M),
        .gt0_drpaddr_in             (9'b0),
        .gt0_drpclk_in              (clk_drp_100M),
        .gt0_drpdi_in               (16'b0),
        .gt0_drpdo_out              (),
        .gt0_drpen_in               (1'b0),
        .gt0_drprdy_out             (),
        .gt0_drpwe_in               (1'b0),
        .gt0_dmonitorout_out        (),
        .gt0_rxpd_in                (2'b0),
        .gt0_txpd_in                (2'b0),
        .gt0_eyescanreset_in        (1'b0),
        .gt0_rxuserrdy_in           (1'b1),
        .gt0_eyescandataerror_out   (),
        .gt0_eyescantrigger_in      (1'b0),
        .gt0_rxusrclk_in            (clk_rxoutclk_bufg[7]),
        .gt0_rxusrclk2_in           (clk_rxoutclk_bufg[7]),
        .gt0_rxdata_out             (gt_rx_data[112 +: 16]),
        .gt0_rxdisperr_out          (),
        .gt0_rxnotintable_out       (rx_not_in_table[7]),
        .gt0_gtxrxp_in              (gtx_rx_p[7]),
        .gt0_gtxrxn_in              (gtx_rx_n[7]),
        .gt0_rxphmonitor_out        (),
        .gt0_rxphslipmonitor_out    (),
        .gt0_rxdfelpmreset_in       (1'b0),
        .gt0_rxmonitorout_out       (),
        .gt0_rxmonitorsel_in        (2'b0),
        .gt0_rxoutclk_out           (clk_rxoutclk[7]),
        .gt0_rxoutclkfabric_out     (),
        .gt0_gtrxreset_in           (1'b0),
        .gt0_rxpmareset_in          (~rx_pma_rst_n[7]),
        .gt0_rxchariscomma_out      (rx_data_is_comma[14 +: 2]),
        .gt0_rxcharisk_out          (rx_data_is_k[7]),
        .gt0_rxresetdone_out        (rx_reset_done[7]),
        .gt0_gttxreset_in           (1'b0),
        .gt0_txuserrdy_in           (1'b1),
        .gt0_txusrclk_in            (clk_txoutclk_bufg[7]),
        .gt0_txusrclk2_in           (clk_txoutclk_bufg[7]),
        .gt0_txelecidle_in          (1'b0),
        // .gt0_txdata_in              (gt_tx_data[112 +: 16]),
        .gt0_txdata_in              (16'hbc3c),
        .gt0_gtxtxn_out             (gtx_tx_n[7]),
        .gt0_gtxtxp_out             (gtx_tx_p[7]),
        .gt0_txoutclk_out           (clk_txoutclk[7]),
        .gt0_txoutclkfabric_out     (),
        .gt0_txoutclkpcs_out        (),
        .gt0_txcharisk_in           (2'b11),
        .gt0_txresetdone_out        (),
        .gt0_qplloutclk_in          (1'b0),
        .gt0_qplloutrefclk_in       (1'b0)
    );

    wire cpll_reset;
    // debug
    vio_1 isntance_vio_1 (
        .clk (clk_gtx_125M),
        .probe_in0 ({
            tx_data_is_k[0],
            tx_data_is_k[1],
            tx_data_is_k[2],
            tx_data_is_k[3],
            tx_data_is_k[4],
            tx_data_is_k[5],
            tx_data_is_k[6],
            tx_data_is_k[7]
        }),
        .probe_out0(cpll_reset)
    );
endmodule
